# used for run the data generation model 

#setwd("~/simulation/data/var1/c4/equal")
#set.seed(12345)
# extract the code for generate data and derived the coeffcients
base::source(file="~/simulation/code/var(1).R")
base::source(file="~/simulation/code/export.data.R")
###
repet=10 # number of replicates for each condition
k=4 # number of intensive longitudinal variables
ncluster=4 # true number of clusters
y0=rep(0,k) # intercept
time=c(50,100,500,1000) # length of ILDs
dist=seq(0.05,0.25,0.05) # distance of two clusters
ef=seq(2,12,2) # used for condition proportion of data generated by var(2)=0
#ef=seq(4,24,4) # used for condition proportion of data generated by var(2) =10%,40%,60%,90%,100%
percent=c(0.25,0.25,0.25,0.25) # relative size of clusters

for(c in ncluster){
  nob=c(60,120,240) # sample size
  
 
  for(n in nob){
    
    for(tp in time){
      
      for (i in ef){
        
        for(j in dist){
          
          a=Sys.time()
          con=export.data(randomstart=10,nob=n,time=tp,percent=percent,k=k,p=1,repet=10,dist=j,ncluster=c,ef=i) ## of var(1)
          # p: temporal order for data generated model 
          #     p=1 when proportion of data following var(2)=0% 
          #     p=2 when proportion of data following var(2)=10%,40%,60%,90%,100%
          write.csv(con[[1]],file = paste0(c,n,tp,i,j,"-lag1.csv"))
          write.csv(con[[2]],file = paste0(c,n,tp,i,j,"-lag2.csv"))
          write.csv(con[[4]],file = paste0(c,n,tp,i,j,"-phi.csv"))
          print(paste0("finishing dist: ", j))
          print(Sys.time()-a)
          print(Sys.time())
          
        }
        print(paste0("finishing ef: ", i))}
      print(paste0("finishing time point: ", tp))}
    print(paste0("finishing nob: ", n))}
}
