#----used for run the clustering algorithms for LO methods with GMM and k-means

setwd("~/simulation/data/var2/c4/minority")
set.seed(12345)
#--load the functions------------------
base::source(file="~/simulation/code/clustering_functions.R")
#------load the data---------------------------------------
path="~/simulation/results/mix/var2/minority/lag1/" # data is LO method for data following VAR(2) model
ncluster=4 # number of clusters
namefiles=c()
files.phi=c()
correlation=c()
k=4 # number of intensive longitudinal variables
dist=seq(0.05,0.25,0.05) # distance between clusters
tp=c(50,100,500,1000) # length of ILDs
nob=c(60,120,240) # sample size
ef=seq(4,24,4) # number of effective coefficients for condition which 
              # the proportion data generated by VAR(2)=10%,40%,60%,90%,100%
#ef=seq(2,12,2) # number of effective coefficients for condition which 
               # the proportion data generated by VAR(2)=0%
for(n in nob){
  for (t in tp){
    for (i in ef){
      for (j in dist){
        name=paste0(ncluster,n,t,i,j,"-lag1.csv") # files names for estimated dynamic coefficients
        namefiles=c(namefiles,name)
        name.phi=paste0(ncluster,n,t,i,j,"-phi.csv") # files names for model generated dynamic coefficients
        files.phi=c(files.phi,name.phi)
      }
    }
  }
}

###

# set.seed(12346)
###

result.m=c()
result=c()

k=4
j=1

# get all the files names for extracted coefficients

percent=c(0.25,0.25,0.25,0.25)# first one is proportion of data following var(2) model
for (n in nob){
  # get the data for each level of sample size
  num.l=(j-1)*120+1
  num.h=j*120
 
  for (i in (num.l:num.h)){
    
    a=Sys.time()
    data=read.csv(namefiles[i])
    data=data[,-1]
    
    phi=read.csv(files.phi[i])
    phi=phi[,-1]
    
    con=cluster.var1.both(data=data,phi=phi,randomstart=10,nob=n,k=k,p=2,repet=10,ncluster=ncluster,percent=percent)

    
    result.m=rbind(result.m,apply(con[[1]],1,mean,na.rm=T))
    result=rbind(result,con[[1]])
    
    write.csv(result,file = paste0(path,n,i,"-result.csv")) # ari and proportion of membership accuracy for each replicates
    write.csv(con[[3]],file = paste0(path,n,i,"-membership.csv")) # predicted membership for each individuals
   
    write.csv(result.m,file = paste0(path,n,i, "-result.m.csv")) # ari and proportion of membership accuracy for each condition
    
    print(paste0("finishing DATA: ", i))
    print(Sys.time()-a)
    print(Sys.time())}
  j=j+1
  print(paste0("finishing nob: ", n))
}